"""agregar metodo_pago, propina, observaciones a turnos y precio_aplicado a turno_servicios

Revision ID: 1a6d0662fd40
Revises: 5d282d3a7e50
Create Date: 2026-06-22 18:30:38.685051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6d0662fd40'
down_revision: Union[str, Sequence[str], None] = '5d282d3a7e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turno_servicios', sa.Column('precio_aplicado', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('turno_servicios', sa.Column('duracion_aplicada', sa.Integer(), nullable=False))
    op.add_column('turnos', sa.Column('metodo_pago', sa.String(length=30), nullable=True))
    op.add_column('turnos', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('turnos', sa.Column('propina', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('turnos', sa.Column('id_barbero_propina', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turnos', 'barberos', ['id_barbero_propina'], ['id_barbero'])
    op.alter_column('turnos', 'estado',
        existing_type=sa.Enum('pendiente', 'confirmado', 'completado', 'cancelado', 'no_asistio'),
        type_=sa.Enum('pendiente', 'confirmado', 'en_proceso', 'completado', 'cancelado', 'no_asistio'),
        existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turnos', type_='foreignkey')
    op.drop_column('turnos', 'id_barbero_propina')
    op.drop_column('turnos', 'propina')
    op.drop_column('turnos', 'observaciones')
    op.drop_column('turnos', 'metodo_pago')
    op.drop_column('turno_servicios', 'duracion_aplicada')
    op.drop_column('turno_servicios', 'precio_aplicado')
    # ### end Alembic commands ###
