"""crear tabla horarios_barbero

Revision ID: 24964a7b9387
Revises: 582cff604fd1
Create Date: 2026-06-22 20:46:18.617453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24964a7b9387'
down_revision: Union[str, Sequence[str], None] = '582cff604fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_barbero',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_barbero', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('pausa_inicio', sa.Time(), nullable=True),
    sa.Column('pausa_fin', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_horario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios_barbero')
    # ### end Alembic commands ###
