"""usuario multi-tenant: email y unique compuesto

Revision ID: 49f0fed91cd9
Revises: 414bab038227
Create Date: 2026-06-23 01:46:37.973592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f0fed91cd9'
down_revision: Union[str, Sequence[str], None] = '414bab038227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_acontecimientos_id_barberia'), 'acontecimientos', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_barberos_id_barberia'), 'barberos', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_carousel_slides_id_barberia'), 'carousel_slides', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_categorias_productos_id_barberia'), 'categorias_productos', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_cierres_caja_id_barberia'), 'cierres_caja', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_clientes_id_barberia'), 'clientes', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_codigos_qr_id_barberia'), 'codigos_qr', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_compras_productos_id_barberia'), 'compras_productos', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_configuracion_id_barberia'), 'configuracion', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_descuentos_caja_id_barberia'), 'descuentos_caja', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_fotos_cliente_id_barberia'), 'fotos_cliente', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_gastos_caja_id_barberia'), 'gastos_caja', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_horarios_barbero_id_barberia'), 'horarios_barbero', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_notificaciones_id_barberia'), 'notificaciones', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_productos_id_barberia'), 'productos', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_proveedores_id_barberia'), 'proveedores', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_servicios_id_barberia'), 'servicios', ['id_barberia'], unique=False)
    op.add_column('turno_servicios', sa.Column('id_barberia', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_turno_servicios_id_barberia'), 'turno_servicios', ['id_barberia'], unique=False)
    op.create_foreign_key(None, 'turno_servicios', 'barberias', ['id_barberia'], ['id_barberia'], ondelete='CASCADE')
    op.create_index(op.f('ix_turnos_id_barberia'), 'turnos', ['id_barberia'], unique=False)
    op.add_column('usuarios', sa.Column('email', sa.String(length=120), nullable=True))
    op.drop_index(op.f('nombre_usuario'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id_barberia'), 'usuarios', ['id_barberia'], unique=False)
    op.create_unique_constraint('uq_usuario_barberia', 'usuarios', ['nombre_usuario', 'id_barberia'])
    op.create_index(op.f('ix_valoraciones_turnos_id_barberia'), 'valoraciones_turnos', ['id_barberia'], unique=False)
    op.create_index(op.f('ix_ventas_productos_id_barberia'), 'ventas_productos', ['id_barberia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_productos_id_barberia'), table_name='ventas_productos')
    op.drop_index(op.f('ix_valoraciones_turnos_id_barberia'), table_name='valoraciones_turnos')
    op.drop_constraint('uq_usuario_barberia', 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_id_barberia'), table_name='usuarios')
    op.create_index(op.f('nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.drop_column('usuarios', 'email')
    op.drop_index(op.f('ix_turnos_id_barberia'), table_name='turnos')
    op.drop_constraint(None, 'turno_servicios', type_='foreignkey')
    op.drop_index(op.f('ix_turno_servicios_id_barberia'), table_name='turno_servicios')
    op.drop_column('turno_servicios', 'id_barberia')
    op.drop_index(op.f('ix_servicios_id_barberia'), table_name='servicios')
    op.drop_index(op.f('ix_proveedores_id_barberia'), table_name='proveedores')
    op.drop_index(op.f('ix_productos_id_barberia'), table_name='productos')
    op.drop_index(op.f('ix_notificaciones_id_barberia'), table_name='notificaciones')
    op.drop_index(op.f('ix_horarios_barbero_id_barberia'), table_name='horarios_barbero')
    op.drop_index(op.f('ix_gastos_caja_id_barberia'), table_name='gastos_caja')
    op.drop_index(op.f('ix_fotos_cliente_id_barberia'), table_name='fotos_cliente')
    op.drop_index(op.f('ix_descuentos_caja_id_barberia'), table_name='descuentos_caja')
    op.drop_index(op.f('ix_configuracion_id_barberia'), table_name='configuracion')
    op.drop_index(op.f('ix_compras_productos_id_barberia'), table_name='compras_productos')
    op.drop_index(op.f('ix_codigos_qr_id_barberia'), table_name='codigos_qr')
    op.drop_index(op.f('ix_clientes_id_barberia'), table_name='clientes')
    op.drop_index(op.f('ix_cierres_caja_id_barberia'), table_name='cierres_caja')
    op.drop_index(op.f('ix_categorias_productos_id_barberia'), table_name='categorias_productos')
    op.drop_index(op.f('ix_carousel_slides_id_barberia'), table_name='carousel_slides')
    op.drop_index(op.f('ix_barberos_id_barberia'), table_name='barberos')
    op.drop_index(op.f('ix_acontecimientos_id_barberia'), table_name='acontecimientos')
    # ### end Alembic commands ###
