"""crear tabla barberias (tenant SaaS)

Revision ID: 575bb1d9e6af
Revises: 7661548a5bfc
Create Date: 2026-06-23 01:34:22.721857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575bb1d9e6af'
down_revision: Union[str, Sequence[str], None] = '7661548a5bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barberias',
    sa.Column('id_barberia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subdominio', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=40), nullable=True),
    sa.Column('email_contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('trial', 'activa', 'suspendida', 'cancelada', name='estadobarberiaenum'), nullable=True),
    sa.Column('trial_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_barberia'),
    sa.UniqueConstraint('subdominio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barberias')
    # ### end Alembic commands ###
