"""agregar documento, direccion y foto a clientes

Revision ID: 5d282d3a7e50
Revises: 99c1c53a2ad6
Create Date: 2026-06-22 18:20:17.231831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d282d3a7e50'
down_revision: Union[str, Sequence[str], None] = '99c1c53a2ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('tipo_documento', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('documento', sa.String(length=30), nullable=True))
    op.add_column('clientes', sa.Column('direccion', sa.String(length=200), nullable=True))
    op.add_column('clientes', sa.Column('foto', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'clientes', ['documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'foto')
    op.drop_column('clientes', 'direccion')
    op.drop_column('clientes', 'documento')
    op.drop_column('clientes', 'tipo_documento')
    # ### end Alembic commands ###
