"""crear tabla codigos_qr

Revision ID: 7661548a5bfc
Revises: 7fa51f1a992d
Create Date: 2026-06-23 00:14:24.983449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7661548a5bfc'
down_revision: Union[str, Sequence[str], None] = '7fa51f1a992d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_qr',
    sa.Column('id_qr', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('sistema', 'barbero', 'personalizado', name='tipoqrenum'), nullable=True),
    sa.Column('url_destino', sa.String(length=500), nullable=False),
    sa.Column('id_barbero', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_qr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigos_qr')
    # ### end Alembic commands ###
