"""crear tabla acontecimientos

Revision ID: 7fa51f1a992d
Revises: c01d1d5eb355
Create Date: 2026-06-23 00:13:02.543352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa51f1a992d'
down_revision: Union[str, Sequence[str], None] = 'c01d1d5eb355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acontecimientos',
    sa.Column('id_acontecimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('cumpleanos', 'aniversario', 'promocion', 'otro', name='tipoacontecimientoenum'), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_acontecimiento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acontecimientos')
    # ### end Alembic commands ###
