"""crear tabla valoraciones_turnos

Revision ID: 80ac80257054
Revises: fe129b5e1325
Create Date: 2026-06-22 23:53:16.797432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ac80257054'
down_revision: Union[str, Sequence[str], None] = 'fe129b5e1325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valoraciones_turnos',
    sa.Column('id_valoracion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('id_barbero', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('estrellas >= 1 AND estrellas <= 5', name='check_estrellas_rango'),
    sa.ForeignKeyConstraint(['id_barbero'], ['barberos.id_barbero'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_valoracion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valoraciones_turnos')
    # ### end Alembic commands ###
