"""crear tabla productos

Revision ID: 8bdbb3a7c595
Revises: cd7c7bf1ca2e
Create Date: 2026-06-22 21:39:37.664156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdbb3a7c595'
down_revision: Union[str, Sequence[str], None] = 'cd7c7bf1ca2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('costo_actual', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('precio_venta', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=80), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias_productos.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
