"""crear tablas planes y suscripciones

Revision ID: a45ce9a23449
Revises: 575bb1d9e6af
Create Date: 2026-06-23 01:35:47.650028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45ce9a23449'
down_revision: Union[str, Sequence[str], None] = '575bb1d9e6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id_plan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_mensual', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_barberos', sa.Integer(), nullable=True),
    sa.Column('max_turnos_mes', sa.Integer(), nullable=True),
    sa.Column('permite_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('permite_pagos_online', sa.Boolean(), nullable=True),
    sa.Column('permite_reportes', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_plan')
    )
    op.create_table('suscripciones',
    sa.Column('id_suscripcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_barberia', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('trial', 'activa', 'vencida', 'cancelada', name='estadosuscripcionenum'), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_barberia'], ['barberias.id_barberia'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_plan'], ['planes.id_plan'], ),
    sa.PrimaryKeyConstraint('id_suscripcion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suscripciones')
    op.drop_table('planes')
    # ### end Alembic commands ###
