"""crear tabla notificaciones

Revision ID: aa5437e2702b
Revises: 80ac80257054
Create Date: 2026-06-22 23:59:38.943652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5437e2702b'
down_revision: Union[str, Sequence[str], None] = '80ac80257054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('info', 'alerta', 'recordatorio', name='tiponotificacionenum'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
