"""crear tablas carousel_slides y fotos_cliente

Revision ID: c01d1d5eb355
Revises: 4908e2ea9f15
Create Date: 2026-06-23 00:07:33.002950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01d1d5eb355'
down_revision: Union[str, Sequence[str], None] = '4908e2ea9f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_slides',
    sa.Column('id_slide', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('subtitulo', sa.String(length=250), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('texto_boton', sa.String(length=50), nullable=True),
    sa.Column('enlace_boton', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_slide')
    )
    op.create_table('fotos_cliente',
    sa.Column('id_foto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_foto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos_cliente')
    op.drop_table('carousel_slides')
    # ### end Alembic commands ###
