"""crear tablas categorias_productos y proveedores

Revision ID: cd7c7bf1ca2e
Revises: 9be174f33b1a
Create Date: 2026-06-22 21:37:41.279839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7c7bf1ca2e'
down_revision: Union[str, Sequence[str], None] = '9be174f33b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_productos',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    op.drop_table('categorias_productos')
    # ### end Alembic commands ###
