"""crear tabla compras_productos

Revision ID: f1ea767ff8fd
Revises: 8bdbb3a7c595
Create Date: 2026-06-22 21:43:56.007052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ea767ff8fd'
down_revision: Union[str, Sequence[str], None] = '8bdbb3a7c595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras_productos',
    sa.Column('id_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('costo_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('factura', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compras_productos')
    # ### end Alembic commands ###
