"""crear tablas de caja: gastos, descuentos y cierres

Revision ID: fe129b5e1325
Revises: 919dcb650765
Create Date: 2026-06-22 23:46:34.338499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe129b5e1325'
down_revision: Union[str, Sequence[str], None] = '919dcb650765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierres_caja',
    sa.Column('id_cierre', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ingresos_turnos', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ingresos_ventas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_propinas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_gastos', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_descuentos', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('balance_final', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cierre'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('descuentos_caja',
    sa.Column('id_descuento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_descuento')
    )
    op.create_table('gastos_caja',
    sa.Column('id_gasto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos_caja')
    op.drop_table('descuentos_caja')
    op.drop_table('cierres_caja')
    # ### end Alembic commands ###
